# This is a basic workflow to help you get started with Actions

name: Publish

env:
  github_token: ${{secrets.API_TOKEN}}

defaults:
  run:
    shell: bash

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # push:
  #   branches: [ master ]
  schedule:
    - cron: "0 2 * * 2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: "Download latest extension"
      run: |
        ./download.bash $github_token
        echo finished downloading
    - name: "Publish to Open VSX Registry"
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
        extensionFile: "rust-analyzer.vsix"
        packagePath: ""
