name: "Publish"


env:
  github_token: ${{secrets.GITHUB_TOKEN}}
on:
  schedule:
    - cron: '0 2 * * 2'

jobs: 
  my_first_job:
    runs-on: ubuntu-20.04
    name: "Publish to open-vsix"
    steps:
      - name: "Download latest extension"
        run: "download.bash"
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: "./rust-analyzer.vsix"